main/urls.py
from django.contrib import admin
from django.urls import path
from reserva.views import reserva_criar,reserva_listar,reserva_detalhar,reserva_remover,index,fazer_reserva

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('form/',fazer_reserva,name='fazer_reserva'),
    path('reserva/',reserva_criar,name='reserva_criar'),
    path('reserva/listar',reserva_listar,name='reserva_listar'),
    path('reserva/detalhar/<int:id>/',reserva_detalhar,name='reserva_detalhar'),
    path('reserva/remover/<int:id>/',reserva_remover,name='reserva_remover'),
]

reserva/models.py
from django.db import models

# Create your models here.
class Reserva(models.Model):
    cnpj = models.CharField(max_length=18)
    nome_empresa = models.CharField(max_length=100)
    categoria_empresa = models.CharField(max_length=100)
    quitado = models.BooleanField()

    def __str__(self):
        return self.nome_empresa

class Stand(models.Model):
    localizacao = models.CharField(max_length=150)
    valor = models.FloatField()
    empresa = models.OneToOneField(Reserva, on_delete=models.CASCADE)

reserva/views.py
from django.shortcuts import render
from django.shortcuts import render,get_object_or_404,redirect
from .models import Reserva
from .form import ReservaForm

# Create your views here.
def reserva_criar(request):
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            form.save()
            form = ReservaForm()
    else:
        form = ReservaForm()

    return render(request, 'core/form.html', {'form': form})

def reserva_listar(request):
    reservas = Reserva.objects.all()
    context ={
        'reservas':reservas
    }
    return render(request, 'core/reservas.html',context)

def reserva_detalhar(request,id):
    reserva = Reserva.objects.get(id=id)
    return render(request,'core/detalhes.html', {'reserva': reserva})

def reserva_remover(request, id):
    aluno = get_object_or_404(Reserva, id=id)
    aluno.delete()
    return redirect('reserva_listar')

def index(request):
    return render(request, 'core/index.html')

# Create your views here.
def fazer_reserva(request):
    return render(request, 'core/form.html')

reserva/templates/core/detalhes.html
{% extends "base.html" %}

{% block title %}
Detalhes da Reserva
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="jumbotron jumbotron-fluid">
                <div class="container">
                    <h1 class="display-4">Detalhe da Reserva</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{reserva.nome_empresa}}</h5>
            <p class="card-text">{{reserva.categoria_empresa}}</p>
            <p class="card-text"><small class="text-muted">{{reserva.cnpj}}</small></p>
            <p class="card-text"><small class="text-muted">{{reserva.quitado}}</small></p>
        </div>
    </div>
{% endblock %}

reserva/templates/core/form.html
{% extends "base.html" %}

{% block title %}Reserva{% endblock %}

{% block content %}
<div class="mt-5">
    <h2>Formulário de reserva</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_cnpj">CNPJ</label>
            <input type="text" name="cnpj" class="form-control" id="id_cnpj">
        </div>
        <div class="form-group">
            <label for="id_nome_empresa">Nome da empresa</label>
            <input type="text" name="nome_empresa" class="form-control" id="id_nome_empresa">
        </div>
        <div class="form-group">
            <label for="id_categoria_empresa">Categoria</label>
            <input type="text" name="categoria_empresa" class="form-control" id="id_categoria_empresa">
        </div>
        <div class="form-check">
            <input type="checkbox" name="quitado" class="form-check-input" id="id_quitado">
            <label class="form-check-label" for="id_quitado">Quitado</label>
        </div>

        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>
{% endblock %}

reserva/templates/core/index.html
{% extends "base.html" %}

{% block title %}Página inicial{% endblock %}

{% block content %}
<h2>Marcos Fábio Carneiro e Silva</h2>
<p>Aluno do IFRN campus Pau dos Ferros; Curso de Informática</p>
{% endblock %}

reserva/templates/core/reservas.html
{% extends "base.html" %}

{% block title %}Lista de Reservas{% endblock %}

{% block content %}
<div class="mt-5">
    <h2>Lista de Reservas</h2>

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Categoria</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Quitado</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for reserva in reservas %}
            <tr>
                <td>{{ reserva.nome_empresa }}</td>
                <td>{{ reserva.categoria_empresa }}</td>
                <td>{{ reserva.cnpj }}</td>
                <td>{{ reserva.quitado }}</td>
                <td>
                    <a href="{% url 'reserva_detalhar' id=reserva.id %}"><i class="fas fa-edit"></i>Detalhar</a>
                    <a href="{% url 'reserva_remover' id=reserva.id %}"><i class="fas fa-trash-alt"></i>Remover</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="mb-3">
        <a href="{% url 'reserva_criar' %}" class="btn btn-primary">Adicionar Nova</a>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #f8f9fa;
            color: #6c757d;
            text-align: center;
            border-top: 1px solid #e5e5e5;
        }
        .navbar-nav {
            width: 100%;
            justify-content: center;
            
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Minha Aplicação</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reserva_listar' %}">Lista reservas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reserva_criar' %}">Fazer reserva</a>
                </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">Disc